Add module variable to allow write permission
cisagov/terraform-state-read-role-tf-module pull request #37
Opened 2024-09-27 15:31 UTC by jsf9k

## 🗣 Description ##

This pull request adds a module variable (`var.read_only`) that allows for the addition of write permissions to the IAM role being created.

## 💭 Motivation and context ##

This change is required because we require a read-write role that allows access to a particular COOL environment's remote state.

Note also that these changes have been made in a way that is backward compatible with the role's previous behavior, so this is a non-breaking change.

## 🧪 Testing ##

All automated tests pass.

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] All relevant repo and/or project documentation has been updated to reflect the changes in this PR.
- [ ] All new and existing tests pass.

2024-09-27 15:46 UTC, dv4harr10 approved these changes

2024-09-27 15:48 UTC, dav3r approved these changes
This looks great to me.  👍 👍 

My only thought is that with this change, the repo and module should now be renamed to something like `terraform-state-access-role-tf-module`, but I'm ok with just creating an issue for that change since it's a bit of a hassle.

2024-09-27 16:19 UTC, mcdonnnj requested changes

2024-09-27 16:19 UTC, mcdonnnj commented on variables.tf
> +  default     = "Allows %s access to the Terraform state at '%s' for the '%s' workspace(s) in the %s S3 bucket."
I don't see an update to `local.role_description` in this PR that reflects this change.

2024-09-27 17:01 UTC, jsf9k commented on variables.tf
> +  default     = "Allows %s access to the Terraform state at '%s' for the '%s' workspace(s) in the %s S3 bucket."
Excellent catch!  See commit 52075df.

2024-09-27 17:04 UTC, jsf9k commented
> This looks great to me. 👍 👍
> 
> My only thought is that with this change, the repo and module should now be renamed to something like `terraform-state-access-role-tf-module`, but I'm ok with just creating an issue for that change since it's a bit of a hassle.

Please see issue #38.

2024-09-27 17:19 UTC, mcdonnnj approved these changes
LGTM ✔

2024-09-27 17:29 UTC, dav3r commented
> Please see issue #38 (and [cisagov/s3-read-role-tf-module#48](https://github.com/cisagov/s3-read-role-tf-module/issues/48)).

Perfect, thanks! 😎

2024-10-01 21:26 UTC, dv4harr10 approved these changes

2024-10-02 02:28 UTC, dav3r approved these changes

2024-10-02 14:33 UTC, merged